#ifndef LSH_COLORS_H
#define LSH_COLORS_H

#define COLOR_START "\033["
#define COLOR_END "m"

#define COLOR_RESET COLOR_START "0" COLOR_END
#define COLOR_GREEN COLOR_START "32" COLOR_END
#define COLOR_RED COLOR_START "31" COLOR_END
#define COLOR_BLUE COLOR_START "36" COLOR_END
#define COLOR_MAGENTA COLOR_START "35" COLOR_END

#endif